"""Added column to model

Revision ID: 2897d0742b89
Revises: 0fdddce5fdf7
Create Date: 2021-03-12 18:38:51.561809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2897d0742b89'
down_revision = '0fdddce5fdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('linked_image', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'linked_image')
    # ### end Alembic commands ###
