"""Added column to memo model

Revision ID: 5f4ce60455f8
Revises: 6ca69e41bc2c
Create Date: 2021-04-23 17:11:13.528793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4ce60455f8'
down_revision = '6ca69e41bc2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'is_deleted')
    # ### end Alembic commands ###
