"""Added column to memo

Revision ID: 6512874e065e
Revises: f2d01eb740c5
Create Date: 2021-03-28 23:20:29.001356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6512874e065e'
down_revision = 'f2d01eb740c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('linked_image', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'linked_image')
    # ### end Alembic commands ###
