"""Added new field to memo model

Revision ID: 6ca69e41bc2c
Revises: 42fb8064357e
Create Date: 2021-04-23 15:56:48.610643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca69e41bc2c'
down_revision = '42fb8064357e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('linked_image', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'linked_image')
    # ### end Alembic commands ###
