"""Added column to memo model

Revision ID: 8cd336cd2e4e
Revises: 6512874e065e
Create Date: 2021-03-29 13:26:27.370232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd336cd2e4e'
down_revision = '6512874e065e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memo', 'is_deleted')
    # ### end Alembic commands ###
